kind = "web"
previewPath = "/"
title = "AV Eventz"
version = "1.0.0"
id = "artifacts/av-eventz"
router = "path"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 24873

[services.development]
run = "pnpm --filter @workspace/av-eventz run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/av-eventz", "run", "build" ]
serve = "static"
publicDir = "artifacts/av-eventz/dist/public"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "24873"
BASE_PATH = "/"
